name: my first workflow

on:
  push:
    branches: ['release/v[1-9]+.[0-9]+']

jobs:
  checkout:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message,'#NORUN') != true
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Railway CLI
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.BE_STRONG }}

    - name: Send data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name: * Chit Su Wai Lin"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email: * e1114086@u.nus.edu"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Matriculation: A0269747H"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\n ${{github.event.repository.html_url}}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "https://${{vars.VAR_RAILWAY_URL}}.up.railway.app"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": " "
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "GO",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "https://${{vars.VAR_RAILWAY_URL}}.up.railway.app",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
