name: my first workflow

on:
  push:
    branches: [Branch2]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Railway CLI
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.BE_STRONG }}

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name: * Chit Su Wai Lin"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email: * e1114086@u.nus.edu"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Matriculation: Axxxxx"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\n repo name"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://laughable-collar-production.up.railway.app>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": " "
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "url": "https://laughable-collar-production.up.railway.app",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
